FROM openjdk:8-jre-alpine
ARG JAR_FILE=spring-micro-business-remoting-0.0.1-SNAPSHOT.jar
ENV APP_FILE $JAR_FILE
ENV APP_HOME /usr/apps
EXPOSE 8000
COPY target/$APP_FILE $APP_HOME/
WORKDIR $APP_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $APP_FILE"]
