apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-09-12T08:14:42Z"
  generation: 12
  labels:
    run: businessremotingdeployment
  name: businessremotingdeployment
  namespace: default
  resourceVersion: "954246"
  selfLink: /apis/apps/v1/namespaces/default/deployments/businessremotingdeployment
  uid: 5f7ff7ed-d535-11e9-8846-42010a8c01b7
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      run: businessremotingdeployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: businessremotingdeployment
    spec:
      containers:
      - image: gcr.io/sillybilly-246306/spring-micro-business-remoting:v1
        imagePullPolicy: IfNotPresent
        name: businessremotingdeployment
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2019-09-13T16:41:31Z"
    lastUpdateTime: "2019-09-13T16:41:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 12
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
